version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into ECR....
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 539920679315.dkr.ecr.ap-northeast-2.amazonaws.com
      - echo Build started on `date`
  build:
    commands:
      - echo Building Docker image...
      - docker build -t front-app .
      - docker tag front-app:latest 539920679315.dkr.ecr.ap-northeast-2.amazonaws.com/front:latest
  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push 539920679315.dkr.ecr.ap-northeast-2.amazonaws.com/front:latest

      - echo Updating ECS task definition...
      - sed -i 's|<image_uri>|539920679315.dkr.ecr.ap-northeast-2.amazonaws.com/front:latest|' ecs-task-definition.json

      - echo Registering new task definition with ECS...
      - aws ecs register-task-definition --cli-input-json file://ecs-task-definition.json

      - echo Updating ECS service...
      - aws ecs update-service --cluster front-backend-cluster --service front-backend-service --force-new-deployment

artifacts:
  files: '**/*'
